import { test, expect } from '@playwright/test';
for (const width of [320, 360, 390, 768, 1024, 1280, 1440]) test(`merch detail and variant ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  await page.goto('/merch');
  await page.getByRole('button', { name: 'Принять', exact: true }).click();
  await expect(page.locator('.club-merch-item').first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `/Users/macbook/alumni-staged-evidence/screenshots/stage3-merch-${width}.png`, fullPage: true });
  await page.getByRole('button', { name: 'Список', exact: true }).click();
  await expect(page.locator('.club-merch-list')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  await page.locator('.club-merch-item h2 a').first().click();
  await page.reload();
  await expect(page.locator('h1')).toBeVisible();
  await page.getByRole('button', { name: 'Выбрать вариант и количество' }).click();
  const dialog = page.locator('[role="dialog"][aria-modal="true"]');
  await expect(dialog).toBeVisible();
  const variants = dialog.locator('button[aria-pressed]:enabled');
  if (await variants.count()) await variants.first().click();
  await page.setViewportSize({ width, height: 500 });
  const add = dialog.getByRole('button', { name: 'В корзину', exact: true });
  await add.scrollIntoViewIfNeeded();
  await add.click({ trial: true });
  await page.screenshot({ path: `/Users/macbook/alumni-staged-evidence/screenshots/stage3-merch-dialog-${width}.png` });
  await Promise.all([page.waitForResponse(r => r.url().endsWith('/api/cart') && r.request().method() === 'POST' && r.ok()), add.click()]);
  await expect(dialog).not.toBeVisible();
  await page.goto('/cart');
  await expect(page.getByText('Корзина пуста', { exact: true })).not.toBeVisible();
});
