import { describe, it, expect, afterAll, vi } from "vitest";
import Fastify from "fastify";
import rateLimit from "@fastify/rate-limit";
import { randomUUID, randomBytes } from "node:crypto";
import { checkoutPool } from "../lib/checkout-store.js";
import { supportRoutes, supportConfig, purgeSupport } from "./support.js";
import { signAdmin } from "../lib/auth.js";
import { env } from "../env.js";
vi.mock("../lib/audit.js",()=>({audit:vi.fn()}));
const enabled=process.env.RUN_SUPPORT_INTEGRATION==="true";
if(enabled&&new URL(process.env.CHECKOUT_DATABASE_URL!).pathname!=="/alumni_staged")throw new Error("Only alumni_staged is allowed");
const pool=enabled?checkoutPool():null;const ids:string[]=[];
async function app(){const a=Fastify();await a.register(supportRoutes);return a;}
function body(){const id=randomUUID();ids.push(id);return {id,key:randomBytes(32).toString("hex"),topic:"account",message:"Тестовое обращение без персональных данных",consent:true,consentVersion:supportConfig().version};}
async function fixture(){const a=await app(),b=body();expect((await a.inject({method:"POST",url:"/support",payload:b})).statusCode).toBe(200);return {a,b};}
afterAll(async()=>{if(pool){await pool.query("DELETE FROM club_support_tickets WHERE id=ANY($1::uuid[])",[ids]);await pool.end();}});
describe.skipIf(!enabled)("Поддержка: реальная БД, доступ и жизненный цикл",()=>{
 it("без согласия и со старой версией не записывает обращение",async()=>{const a=await app(),b=body();expect((await a.inject({method:"POST",url:"/support",payload:{...b,consent:false}})).statusCode).toBe(400);expect((await a.inject({method:"POST",url:"/support",payload:{...b,consentVersion:"old"}})).statusCode).toBe(409);expect((await pool!.query("SELECT id FROM club_support_tickets WHERE id=$1",[b.id])).rowCount).toBe(0);await a.close();});
 it("повтор и конкурирующее создание сохраняют одну запись и текст согласия",async()=>{const a=await app(),b=body();const results=await Promise.all([a.inject({method:"POST",url:"/support",payload:b}),a.inject({method:"POST",url:"/support",payload:b})]);expect(results.map(r=>r.statusCode)).toEqual([200,200]);const row=(await pool!.query("SELECT * FROM club_support_tickets WHERE id=$1",[b.id])).rows[0];expect(row.messages).toHaveLength(1);expect(row.key_hash).not.toBe(b.key);expect(row.consent_text).toBe(supportConfig().consent);expect(row.consent_at).toBeTruthy();expect((await a.inject({method:"POST",url:"/support",payload:{...b,message:"Другой текст сообщения"}})).statusCode).toBe(409);await a.close();});
 it("чужой ключ не читает, не дополняет и не удаляет переписку",async()=>{const {a,b}=await fixture();const headers={"x-support-key":"0".repeat(64)};expect((await a.inject({url:`/support/${b.id}`,headers})).statusCode).toBe(404);expect((await a.inject({method:"POST",url:`/support/${b.id}/messages`,headers,payload:{message:"Чужое сообщение"}})).statusCode).toBe(409);expect((await a.inject({method:"DELETE",url:`/support/${b.id}`,headers})).statusCode).toBe(404);const r=await a.inject({url:`/support/${b.id}`,headers:{"x-support-key":b.key}});expect(r.headers["cache-control"]).toBe("no-store");expect(r.json().key_hash).toBeUndefined();await a.close();});
 it("гость и редактор не получают ПД из админки; администратор отвечает",async()=>{const {a,b}=await fixture();expect((await a.inject({url:"/admin/support"})).statusCode).toBe(401);const editor={authorization:`Bearer ${signAdmin(randomUUID(),"editor")}`};expect((await a.inject({url:"/admin/support",headers:editor})).statusCode).toBe(403);expect((await a.inject({method:"PATCH",url:`/admin/support/${b.id}`,headers:editor,payload:{status:"closed"}})).statusCode).toBe(403);const admin={authorization:`Bearer ${signAdmin(randomUUID(),"admin")}`};expect((await a.inject({method:"PATCH",url:`/admin/support/${b.id}`,headers:admin,payload:{message:"Ответ сотрудника поддержки",status:"answered"}})).statusCode).toBe(200);const r=await a.inject({url:`/support/${b.id}`,headers:{"x-support-key":b.key}});expect(r.json().messages[1].text).toBe("Ответ сотрудника поддержки");await a.close();});
 it("отзыв удаляет запись, истечение срока закрывает чтение и удаляется очисткой",async()=>{const {a,b}=await fixture();expect((await a.inject({method:"DELETE",url:`/support/${b.id}`,headers:{"x-support-key":b.key}})).statusCode).toBe(200);expect((await pool!.query("SELECT id FROM club_support_tickets WHERE id=$1",[b.id])).rowCount).toBe(0);const c=body();await a.inject({method:"POST",url:"/support",payload:c});await pool!.query("UPDATE club_support_tickets SET expires_at=now()-interval '1 second' WHERE id=$1",[c.id]);expect((await a.inject({url:`/support/${c.id}`,headers:{"x-support-key":c.key}})).statusCode).toBe(404);await purgeSupport();expect((await pool!.query("SELECT id FROM club_support_tickets WHERE id=$1",[c.id])).rowCount).toBe(0);await a.close();});
 it("ограничивает частоту создания",async()=>{const a=Fastify();await a.register(rateLimit);await a.register(supportRoutes);for(let i=0;i<3;i++)expect((await a.inject({method:"POST",url:"/support",payload:body()})).statusCode).toBe(200);expect((await a.inject({method:"POST",url:"/support",payload:body()})).statusCode).toBe(429);await a.close();});
 it("production без оператора не принимает обращение",async()=>{const old=env.APP_ENV;const name=env.SUPPORT_OPERATOR_NAME;try{env.APP_ENV="production";env.SUPPORT_OPERATOR_NAME="";const a=await app();expect(supportConfig().enabled).toBe(false);expect((await a.inject({method:"POST",url:"/support",payload:body()})).statusCode).toBe(503);await a.close();}finally{env.APP_ENV=old;env.SUPPORT_OPERATOR_NAME=name;}});
});
