FIELDS = {
    "programs": [
        ("title", "Название", "text"),
        ("direction", "Направление", "text"),
        ("format", "Формат", "online|offline|blended"),
        ("duration", "Продолжительность", "text"),
        ("price", "Цена, копейки", "number"),
        ("description", "Описание", "textarea"),
        ("cover", "Обложка", "text"),
        ("start", "Начало", "text"),
        ("document", "Документ", "text"),
        ("status", "Статус", "published|draft|archived"),
    ],
    "products": [
        ("title", "Название", "text"),
        ("category", "Категория", "text"),
        ("price", "Цена, копейки", "number"),
        ("stock", "Остаток", "number"),
        ("description", "Описание", "textarea"),
        ("images", "Ссылки на фотографии, JSON", "json"),
        ("variants_json", "Размеры, цвета и остатки, JSON", "json"),
        ("status", "Статус", "published|draft|archived"),
    ],
    "news": [
        ("title", "Заголовок", "text"),
        ("excerpt", "Краткое описание", "textarea"),
        ("body", "Текст", "textarea"),
        ("status", "Статус", "published|draft"),
    ],
    "events": [
        ("title", "Название", "text"),
        ("description", "Описание", "textarea"),
        ("starts_at", "Дата и время ISO 8601", "text"),
        ("location", "Место", "text"),
        ("cover", "Обложка", "text"),
        ("reg_url", "Внешняя регистрация", "text"),
        ("format", "Формат", "offline|online"),
        ("points", "Баллы за участие", "number"),
        ("status", "Статус", "published|draft|done|canceled"),
    ],
    "podcasts": [
        ("title", "Название", "text"),
        ("description", "Описание", "textarea"),
        ("cover", "Обложка", "text"),
        ("audio_url", "Аудиофайл или ссылка", "text"),
        ("video_url", "RuTube", "text"),
        ("duration", "Продолжительность", "text"),
        ("is_free", "Открытый выпуск", "checkbox"),
        ("sort", "Порядок", "number"),
        ("status", "Статус", "published|draft"),
    ],
    "timeline": [
        ("year", "Год", "text"),
        ("title", "Название", "text"),
        ("text", "Текст", "textarea"),
        ("metric", "Показатель", "text"),
        ("sort", "Порядок", "number"),
        ("status", "Статус", "published|draft"),
    ],
}
LABELS = {
    "dpo": "Программы ДПО",
    "merch": "Мерч",
    "podcast": "Подписка на подкасты",
    "online": "Онлайн",
    "offline": "Очно",
    "blended": "Смешанный",
    "published": "Опубликовано",
    "draft": "Черновик",
    "archived": "В архиве",
    "done": "Завершено",
    "canceled": "Отменено",
    "new": "Новая",
    "confirmed": "Подтверждена",
    "in_progress": "В работе",
    "expired": "Истёк резерв",
    "succeeded": "Оплачено",
    "pending": "На проверке",
    "verified": "Подтверждено",
    "rejected": "Отклонено",
    "open": "Открыто",
    "answered": "Отвечено",
    "closed": "Закрыто",
    "dismissed": "Скрыто",
    "imported": "Импортировано",
}
METRICS = {
    "new_orders": "Новые заявки",
    "orders_count": "Всего заявок",
    "orders_paid": "Оплаченные заявки",
    "pending_verifications": "Ожидают проверки",
    "alumni_count": "Выпускники",
    "alumni_verified": "Верифицированы",
    "points_total": "Баллы клуба",
    "programs_actual": "Открытый набор ДПО",
    "programs_total": "Программы ДПО",
    "products_count": "Товары",
    "news_count": "Новости",
    "friendships": "Дружеские связи",
    "friend_requests": "Приглашения",
    "podcasts_count": "Подкасты",
    "podcast_subscribers": "Подписчики подкастов",
    "push_subs_count": "Уведомления",
    "joins": "Заявки на вступление",
    "verified_in_range": "Проверены за период",
    "registers": "Регистрации",
    "orders_created": "Оформлены заявки",
    "orders_new": "Новые заявки",
    "rsvps": "Записи на события",
    "podcast_plays": "Прослушивания",
    "achievements_granted": "Достижения",
    "friendships_new": "Новые связи",
    "push_subs_new": "Новые подписчики",
    "referrals_ledger": "Баллы за приглашения",
    "referrals_alumni": "Пришли по приглашению",
    "login_ok": "Успешные входы",
    "login_fail": "Неудачные входы",
    "login_locked": "Блокировки входа",
    "support_open": "Открытые обращения",
    "support_created": "Новые обращения",
    "verified_ratio": "Доля проверенных выпускников",
}
